### ISSUE TITLE
Project Complete: Debrief

### ISSUE THREAD

**Issue by SteelMatrix** [ece-231l-fall-2019/week-4-complex-cong-nguyen-monday-lab#17]
Excellent job, @cnguyen1209!
We've completed the task required of us in time for extra credit. I thank you for putting forth so much effort to make this achievable. I will email @crowleydi in a few minutes, with you CC'd, in order to notify him that we have completed our work.
Thank you once again,
@SteelMatrix

**Comment by cnguyen1209** [comment]
Thank you so much @SteelMatrix. 
I really appreciate you being my partner. You help me a lot.
Have a good night,
@cnguyen1209

**Comment by SteelMatrix** [comment]
No problem @cnguyen1209,
You have a good evening as well
