### ISSUE TITLE
Error in Compiling: Variable Mismatch

### ISSUE THREAD

**Issue by SteelMatrix** [ece-231l-fall-2019/week-4-complex-cong-nguyen-monday-lab#9]
Hello @cnguyen1209,
When I began compiling to test some of your functions, I received an error. The error states that in the != and == operators, the variable used is "a.img()" I think that this is supposed to be "a.imag()". This is also repeated for the variable "b". If you can, could you please fix this? If not, I can fix it if you let me know.
Thank you,
@SteelMatrix

**Comment by cnguyen1209** [comment]
Thank you @SteelMatrix. You are right. That must be "a.imag()" maybe I did type too fast and missed a word. I'll fix it and make a pull request again.

**Comment by cnguyen1209** [comment]
@SteelMatrix I have already fixed it and merged it. Please check.
Thank you.

**Comment by SteelMatrix** [comment]
Works great now, @cnguyen1209! Thanks for the fix!
@SteelMatrix
